# Generated by Django 2.2.19 on 2021-06-04 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Barisal', 'Barisal'), ('Dhaka North', 'Dhaka North'), ('Dhaka South', 'Dhaka South')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=100)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('strength', models.CharField(blank=True, max_length=20)),
                ('manufactured_by', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.FloatField()),
                ('pack_price', models.FloatField()),
                ('indications', models.CharField(blank=True, max_length=500)),
                ('therapeutic_class', models.CharField(blank=True, max_length=500)),
                ('pharmacology', models.CharField(blank=True, max_length=500)),
                ('dosag_and_administration', models.CharField(blank=True, max_length=700)),
                ('interaction', models.CharField(blank=True, max_length=500)),
                ('contraindications', models.CharField(blank=True, max_length=500)),
                ('side_effects', models.CharField(blank=True, max_length=500)),
                ('pregnancy_and_lactation', models.CharField(blank=True, max_length=500)),
                ('precautions_and_warnings', models.CharField(blank=True, max_length=500)),
                ('overdose_effects', models.CharField(blank=True, max_length=500)),
                ('storage_conditions', models.CharField(blank=True, max_length=500)),
                ('Catagory', models.CharField(blank=True, choices=[('BABY', 'Baby Product'), ('FEMALE', 'Female product'), ('MALE', 'Male product'), ('SEX', 'Sexual product')], max_length=20)),
                ('product_image', models.ImageField(blank=True, upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateTimeField(auto_now=True)),
                ('otp', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('cancel', 'cancel'), ('prepairing', 'prepairing'), ('on the way', 'on the way'), ('delivered', 'delivered')], default='pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medco_com_bd.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medco_com_bd.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medco_com_bd.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
