# Generated by Django 2.2.19 on 2021-06-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medco_com_bd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='order_date_time',
        ),
    ]
