# Generated by Django 2.2.19 on 2021-06-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medco_com_bd', '0002_remove_status_order_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='order_date_no_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
