# Generated by Django 2.2.24 on 2021-11-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medco_com_bd', '0003_auto_20210605_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pack_price',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
