# Generated by Django 2.2.24 on 2021-11-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medco_com_bd', '0004_auto_20211112_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
