# Generated by Django 2.2.24 on 2021-11-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medco_com_bd', '0005_product_small_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='overdose_effects',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
